--- #YAML:1.0
name:                     Test-JSON-Meta
version:                  0.14
abstract:                 Validate your CPAN META.json files
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
  Test::CPAN::Meta::JSON: 0.10
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  IO::File:               0
  Test::More:             0.70

provides:
  Test::JSON::Meta:
    file:     lib/Test/JSON/Meta.pm
    version:  0.14
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-JSON-Meta
  repository: http://github.com/barbie/Test-JSON-Meta

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
