--- #YAML:1.0
name:                     Test-JSON-Meta
version:                  0.11
abstract:                 A test module to validate a CPAN META.json file.
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  Test::More:             0.62
  Test::CPAN::Meta::JSON: 0.10
recommends:
  Test::More:             0.70
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
  Test::CPAN::Meta:       0.13
build_requires:
  Test::More:             0.70

provides:
  Test::JSON::Meta:
    file:     lib/Test/JSON/Meta.pm
    version:  0.11
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-JSON-Meta

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
